version: "3"
services:
  database.postgres:
    image: sameersbn/postgresql:latest
    container_name: postgres
    environment:
      - PG_PASSWORD=ttrss
      - DB_EXTENSION=pg_trgm
    volumes:
      - /root/ttrss/data/:/var/lib/postgresql/
    restart: always

  service.rss:
    image: wangqiru/ttrss:latest
    container_name: ttrss
    ports:
      - 10483:80
    environment:
      - SELF_URL_PATH=http://106.15.75.239:10483/
      - DB_HOST=database.postgres
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=ttrss
    stdin_open: true
    tty: true
    restart: always
    command: sh -c 'sh /wait-for database.postgres:5432 -- php /configure-db.php && exec s6-svscan /etc/s6/'

# set Mercury Parser API endpoint to `service.mercury:3000` on TTRSS plugin setting page
  service.mercury:
    image: wangqiru/mercury-parser-api:latest
    container_name: mercury
    expose:
      - 3000
    restart: always

# set OpenCC API endpoint to `service.opencc:3000` on TTRSS plugin setting page
  service.opencc:
    image: wangqiru/opencc-api-server:latest
    container_name: opencc
    environment:
      NODE_ENV: production
    expose:
      - 3000
    restart: always